-- Adding some entries to populate the data base in dev mode
    INSERT INTO Tasks(title, description, priority) VALUES ('DB initialization script', 'You should create an SQL script that allows to init your database', 2);
    INSERT INTO Tasks(title, description, priority) VALUES ('CRUD functions in app', 'Write the app code to connect to your database and perform CRUD operations', 1);
	INSERT INTO Tasks(title, description, priority) VALUES ('Workout every saturday', 'You have to take care of yourself and your health so do some workout', 3);