version: '3'

services:

  web:
    build: ./pythonWebApp/
    ports:
      - "5000:5000"
    volumes:
      - ./pythonWebApp:/code
    networks:
      application_net:
        ipv4_address: 172.18.0.3
    depends_on: 
      - sql-server

  sql-server:
    image: mysql:8.0.2
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
    ports:
      # port 3306 on the container to 3308 of host OS
      - "3306:3306"
    networks:
      application_net:
        ipv4_address: 172.18.0.4
    volumes:
      - "./database/scripts:/SQL_Scripts"
      - "./database/data:/var/lib/mysql"
  
  
  db_manager:
    container_name: db_manager
    image: adminer
    ports:
      - "9000:8080"
    networks:
      application_net:
        ipv4_address: 172.18.0.5


networks:
  application_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1